version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR $IMAGE_REPO_URI
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO_URI/IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI/IMAGE_NAME:$IMAGE_TAG
