version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo `date` > hello.txt
      - echo "hello buildspec" >> hello.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello.txt
