version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Amazon ECR $IMAGE_REPO_URI
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $LOCAL_TAG
      - export LOCAL_TAG=$IMAGE_NAME:$IMAGE_TAG 
      - export IMAGE_URL=$IMAGE_REPO_URI/$LOCAL_TAG
      - docker build -f server.Dockerfile -t $LOCAL_TAG .
      - docker tag $LOCAL_TAG $IMAGE_URL
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image $IMAGE_URL
      - docker push $IMAGE_URL
